// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService.Data.Models;

public partial class AppointmentDetail
{
    public int AppointmentId { get; set; }

    public int PetId { get; set; }

    public int ServiceId { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual Pet Pet { get; set; }

    public virtual Service Service { get; set; }
}