// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE173565ConsoleEFApp.Models;

public partial class AppointmentDetail
{
    public int AppointmentId { get; set; }

    public int PetId { get; set; }

    public int ServiceId { get; set; }
}