// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService.Data.Models;

public partial class MedicalHistory
{
    public int HistoryId { get; set; }

    public int AppointmentId { get; set; }

    public string Information { get; set; }

    public string TreatmentResult { get; set; }
}