// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService.Data.Models;

public partial class Pet
{
    public int PetId { get; set; }

    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public int Age { get; set; }

    public string Gender { get; set; }

    public string VaccineStatus { get; set; }
}